
title: Aayush Agarwal
email: ayush.agarwalmng@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A computer program does what you tell it to do, not what you want it to do.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  KylixMedusa

author:
    name: Aayush Agarwal
    email: ayush.agarwalmng@gmail.com
social:
  github: KylixMedusa
  instagram: KylixMedusa
  facebook: ayush.agarwalmng.com
  linkedin: ayush.agarwalmng.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
port: 8080
timezone: Asia/Kolkata

# Exclude from processing.
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    -  Readme.md
    -  favicon.ico
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
